### ISSUE TITLE
Assorted errors

### ISSUE THREAD

**Issue by xhevahir** [flothesof/SongCreator#1]
Hi, I was hoping to use this program to make new Songsmith chord and melody matrices from [this MusicXML collection](https://musescore.org/en/node/38081#comment-966745) but I keep getting various errors that I don't know how to address; I figured I'd list them here. The first is that running the folder analysis on this repo's wikifonia folder only shows empty graphs. The second: running melody or chord analysis on one of the included files gives the TypeError message, "setText(self, str): argument 1 has unexpected type 'tuple'. Also, starting SongCreator.py is giving Qt-related messages: "Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created."

I'm using Python 3.5.4, by the way, on Windows. When I used Python 3.6.9 I kept getting a different error about how the function that reads a zip file was expecting bytes and not strings.

**Comment by flothesof** [comment]
Hi, 
thanks for opening this issue.
Unfortunately, the project is not maintained anymore (although I still find it interesting). 
The probable reason for the errors is that the underlying libraries have evolved and so some of the code must be rewritten... 
Regards,
Florian

**Comment by flothesof** [comment]
I've just pushed a (likely) fix for the errors you reported. The interface now works again for me with Python 3.7, PyQt5. Can you try it?

**Comment by xhevahir** [comment]
Looks like it works!

**Comment by xhevahir** [comment]
I made a bunch of changes last week to work around the different errors I encountered. The code is very messy, though.

Edit: I seem to be unable to attach the files to this thread. That feature is not working as advertised. And gist don't allow you to paste code into their editor. Incredible. I'll try pastie. Hopefully it won't be too inconvenient to read from.

Here's MusicXML_utility.py : https://www.pastiebin.com/5e265389ea12b
And SongCreator.py : https://www.pastiebin.com/5e265416265a5

**Comment by xhevahir** [comment]
x-special/nautilus-clipboard
copy
file:///home/wade/Desktop/SongCreator.py

**Comment by xhevahir** [comment]
I'm guessing that scores with key changes will mess up the results. Since I couldn't figure out how a way to transpose scores that have key changes, I wrote a script that (slowly!) counts single-key scores and multiple-key scores. It uses the music21 library.
https://www.pastiebin.com/5e266b4322997 .
If I were to make further use of it I would use music21's key.analyze feature (probably with the Bellman-Budge algorithm) to determine the key of scores with empty key signatures, i.e. in C major / A minor.

**Comment by flothesof** [comment]
Thanks for your contribution. I'm not sure what do with it.
On the one hand, I think it's great you're willing to experiment with this, on the other I don't have any plans maintaining the tool.
Maybe you could fork the project and modify it as you like? What do you think?

**Comment by xhevahir** [comment]
Sorry for taking so long to reply. I've been taking an interest in this project again, and, since I've learned that the bugs in Songsmith are probably never going to be fixed, I'm thinking about working on a replacement for that program. It would be slow going, however, since I've never forked a project, nor even written anything bigger than a small script. Thanks for making this, by the way.
