### ISSUE TITLE
Printing matrices to file?

### ISSUE THREAD

**Issue by xhevahir** [flothesof/SongCreator#3]
I'm hoping to create model files that I could try out in Songsmith. Is there any easy way to print the matrices to a text file? It looks like SongCreator creates numpy arrays, but I've never used numpy and I don't know if there's an easy way to print them.

**Comment by xhevahir** [comment]
OK, so it looks like the chord_transition_matrix and melody_observation_matrix are just lists of lists, which you can flatten and then print out.

**Comment by flothesof** [comment]
I couldn't agree more. Thank you.
